// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateSample implements createSample operation.
//
// Create a new sample item.
//
// POST /samples
func (UnimplementedHandler) CreateSample(ctx context.Context, req *CreateSampleRequestSchema) (r CreateSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteSample implements deleteSample operation.
//
// Delete a specific sample item.
//
// DELETE /samples/{id}
func (UnimplementedHandler) DeleteSample(ctx context.Context, params DeleteSampleParams) (r DeleteSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// Health implements health operation.
//
// Health.
//
// GET /health
func (UnimplementedHandler) Health(ctx context.Context) (r HealthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListSample implements listSample operation.
//
// Get all sample items.
//
// GET /samples
func (UnimplementedHandler) ListSample(ctx context.Context) (r ListSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ReadSample implements readSample operation.
//
// Read a specific sample item.
//
// GET /samples/{id}
func (UnimplementedHandler) ReadSample(ctx context.Context, params ReadSampleParams) (r ReadSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSample implements updateSample operation.
//
// Update a specific sample item.
//
// PUT /samples/{id}
func (UnimplementedHandler) UpdateSample(ctx context.Context, req *UpdateSampleRequestSchema, params UpdateSampleParams) (r UpdateSampleRes, _ error) {
	return r, ht.ErrNotImplemented
}
