// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"

	"github.com/google/uuid"
)

// Ref: #/components/schemas/CreateSampleRequestSchema
type CreateSampleRequestSchema struct {
	// Message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *CreateSampleRequestSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *CreateSampleRequestSchema) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/CreateSampleResponseSchema
type CreateSampleResponseSchema struct {
	Sample Sample `json:"sample"`
}

// GetSample returns the value of Sample.
func (s *CreateSampleResponseSchema) GetSample() Sample {
	return s.Sample
}

// SetSample sets the value of Sample.
func (s *CreateSampleResponseSchema) SetSample(val Sample) {
	s.Sample = val
}

func (*CreateSampleResponseSchema) createSampleRes() {}

// DeleteSampleNoContent is response for DeleteSample operation.
type DeleteSampleNoContent struct{}

func (*DeleteSampleNoContent) deleteSampleRes() {}

// Ref: #/components/schemas/ErrorResponseSchema
type ErrorResponseSchema struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *ErrorResponseSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *ErrorResponseSchema) SetMessage(val string) {
	s.Message = val
}

func (*ErrorResponseSchema) createSampleRes() {}
func (*ErrorResponseSchema) deleteSampleRes() {}
func (*ErrorResponseSchema) healthRes()       {}
func (*ErrorResponseSchema) listSampleRes()   {}
func (*ErrorResponseSchema) readSampleRes()   {}
func (*ErrorResponseSchema) updateSampleRes() {}

// Ref: #/components/schemas/HealthResponseSchema
type HealthResponseSchema struct {
	// Message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *HealthResponseSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *HealthResponseSchema) SetMessage(val string) {
	s.Message = val
}

func (*HealthResponseSchema) healthRes() {}

// Ref: #/components/schemas/ListSampleResponseSchema
type ListSampleResponseSchema struct {
	Samples []Sample `json:"samples"`
}

// GetSamples returns the value of Samples.
func (s *ListSampleResponseSchema) GetSamples() []Sample {
	return s.Samples
}

// SetSamples sets the value of Samples.
func (s *ListSampleResponseSchema) SetSamples(val []Sample) {
	s.Samples = val
}

func (*ListSampleResponseSchema) listSampleRes() {}

// Ref: #/components/schemas/ReadSampleResponseSchema
type ReadSampleResponseSchema struct {
	Sample Sample `json:"sample"`
}

// GetSample returns the value of Sample.
func (s *ReadSampleResponseSchema) GetSample() Sample {
	return s.Sample
}

// SetSample sets the value of Sample.
func (s *ReadSampleResponseSchema) SetSample(val Sample) {
	s.Sample = val
}

func (*ReadSampleResponseSchema) readSampleRes() {}

// Ref: #/components/schemas/Sample
type Sample struct {
	// The ID of the sample item.
	ID uuid.UUID `json:"id"`
	// Message.
	Message string `json:"message"`
	// The date and time when the sample item was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the sample item was updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// GetID returns the value of ID.
func (s *Sample) GetID() uuid.UUID {
	return s.ID
}

// GetMessage returns the value of Message.
func (s *Sample) GetMessage() string {
	return s.Message
}

// GetCreatedAt returns the value of CreatedAt.
func (s *Sample) GetCreatedAt() time.Time {
	return s.CreatedAt
}

// GetUpdatedAt returns the value of UpdatedAt.
func (s *Sample) GetUpdatedAt() time.Time {
	return s.UpdatedAt
}

// SetID sets the value of ID.
func (s *Sample) SetID(val uuid.UUID) {
	s.ID = val
}

// SetMessage sets the value of Message.
func (s *Sample) SetMessage(val string) {
	s.Message = val
}

// SetCreatedAt sets the value of CreatedAt.
func (s *Sample) SetCreatedAt(val time.Time) {
	s.CreatedAt = val
}

// SetUpdatedAt sets the value of UpdatedAt.
func (s *Sample) SetUpdatedAt(val time.Time) {
	s.UpdatedAt = val
}

// Ref: #/components/schemas/UpdateSampleRequestSchema
type UpdateSampleRequestSchema struct {
	// Message.
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *UpdateSampleRequestSchema) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *UpdateSampleRequestSchema) SetMessage(val string) {
	s.Message = val
}

// Ref: #/components/schemas/UpdateSampleResponseSchema
type UpdateSampleResponseSchema struct {
	Sample Sample `json:"sample"`
}

// GetSample returns the value of Sample.
func (s *UpdateSampleResponseSchema) GetSample() Sample {
	return s.Sample
}

// SetSample sets the value of Sample.
func (s *UpdateSampleResponseSchema) SetSample(val Sample) {
	s.Sample = val
}

func (*UpdateSampleResponseSchema) updateSampleRes() {}
