// Code generated by ogen, DO NOT EDIT.
package api

type CreateSampleRes interface {
	createSampleRes()
}

type DeleteSampleRes interface {
	deleteSampleRes()
}

type HealthRes interface {
	healthRes()
}

type ListSampleRes interface {
	listSampleRes()
}

type ReadSampleRes interface {
	readSampleRes()
}

type UpdateSampleRes interface {
	updateSampleRes()
}
